mmd_bone_map = {
    "all_parents_bone": "全ての親",
    "center_bone": "センター",
    "groove_bone": "グルーブ",
    "hip_bone": "腰",
    "upper_body_bone": "上半身",
    "upper_body2_bone": "上半身2",
    "neck_bone": "首",
    "head_bone": "頭",
    "left_shoulder_bone": "左肩",
    "right_shoulder_bone": "右肩",
    "left_upper_arm_bone": "左腕",
    "right_upper_arm_bone": "右腕",
    "left_lower_arm_bone": "左ひじ",
    "right_lower_arm_bone": "右ひじ",
    "left_hand_bone": "左手首",
    "right_hand_bone": "右手首",
    "lower_body_bone": "下半身",
    "left_thigh_bone": "左足",
    "right_thigh_bone": "右足",
    "left_calf_bone": "左ひざ",
    "right_calf_bone": "右ひざ",
    "left_foot_bone": "左足首",
    "right_foot_bone": "右足首",
    "left_toe_bone": "左足先EX",
    "right_toe_bone": "右足先EX",
    "control_center_bone": "操作中心",
    "left_eye_bone": "左目",
    "right_eye_bone": "右目",
    "left_thumb_0": "左親指０",
    "left_thumb_1": "左親指１",
    "left_thumb_2": "左親指２",
    "right_thumb_0": "右親指０",
    "right_thumb_1": "右親指１",
    "right_thumb_2": "右親指２",
    "left_index_1": "左人指１",
    "left_index_2": "左人指２",
    "left_index_3": "左人指３",
    "right_index_1": "右人指１",
    "right_index_2": "右人指２",
    "right_index_3": "右人指３",
    "left_middle_1": "左中指１",
    "left_middle_2": "左中指２",
    "left_middle_3": "左中指３",
    "right_middle_1": "右中指１",
    "right_middle_2": "右中指２",
    "right_middle_3": "右中指３",
    "left_ring_1": "左薬指１",
    "left_ring_2": "左薬指２",
    "left_ring_3": "左薬指３",
    "right_ring_1": "右薬指１",
    "right_ring_2": "右薬指２",
    "right_ring_3": "右薬指３",
    "left_pinky_1": "左小指１",
    "left_pinky_2": "左小指２",
    "left_pinky_3": "左小指３",
    "right_pinky_1": "右小指１",
    "right_pinky_2": "右小指２",
    "right_pinky_3": "右小指３",
}
mmd_bone_group = [
    {
        "name": "センター",
        "bones": [
            "全ての親",
            "センター",
            "グルーブ",
            "腰",
            "操作中心"
        ]
    },
    {
        "name": "ＩＫ",
        "bones": [
            "右足IK親",
            "右足ＩＫ",
            "右つま先ＩＫ",
            "左足IK親",
            "左足ＩＫ",
            "左つま先ＩＫ"
        ]
    },
    {
        "name": "体(上)",
        "bones": [
            "上半身",
            "上半身1",
            "上半身2",
            "首",
            "頭",
            "右目",
            "左目",
            "両目",
            "左眉中",
            "右眉中",
            "右眉頭",
            "左眉頭",
            "右眉尾",
            "左眉尾",
            "上齿",
            "下齿",
            "舌1",
            "舌2",
            "舌3",
            "舌4"
        ]
    },
    {
        "name": "腕",
        "bones": [
            "左肩P",
            "左肩",
            "左腕",
            "左腕捩",
            "左ひじ",
            "左手捩",
            "左手首",
            "左ダミー",
            "右肩P",
            "右肩",
            "右腕",
            "右腕捩",
            "右ひじ",
            "右手捩",
            "右手首",
            "右ダミー"
        ]
    },
    {
        "name": "指",
        "bones": [
            "左親指０",
            "左親指１",
            "左親指２",
            "左人指１",
            "左人指２",
            "左人指３",
            "左中指１",
            "左中指２",
            "左中指３",
            "左薬指１",
            "左薬指２",
            "左薬指３",
            "左小指１",
            "左小指２",
            "左小指３",
            "右親指０",
            "右親指１",
            "右親指２",
            "右人指１",
            "右人指２",
            "右人指３",
            "右中指１",
            "右中指２",
            "右中指３",
            "右薬指１",
            "右薬指２",
            "右薬指３",
            "右小指１",
            "右小指２",
            "右小指３"
        ]
    },
    {
        "name": "体(下)",
        "bones": [
            "下半身"
        ]
    },
    {
        "name": "足",
        "bones": [
            "左足",
            "左ひざ",
            "左足首",
            "左つま先",
            "左足D",
            "左ひざD",
            "左足首D",
            "左足先EX",
            "右足",
            "右ひざ",
            "右足首",
            "右つま先",
            "右足D",
            "右ひざD",
            "右足首D",
            "右足先EX"
        ]
    },
    {
        "name": "その他",
        "bones": [
            "右目先",
            "左目先"
        ]
    }
]